version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: outline
      POSTGRES_PASSWORD: outline
      POSTGRES_DB: outline
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6

  outline:
    image: outlinewiki/outline:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "3005:3000"
    environment:
      DATABASE_URL: postgres://outline:outline@postgres:5432/outline
      REDIS_URL: redis://redis:6379
      URL: http://localhost:3005
      COLLABRATION_URL: http://localhost:3005
      SECRET_KEY: ceca45be33647e7bc39547995759ed2fd3de6c3953af77039a5354102678e5d8
      UTILS_SECRET: db630ed652633d93d65ed0345106704ee42a4fc64d4cb4fdf10231bf5c414951
      PGSSLMODE: disable
    restart: always

volumes:
  pgdata:
